# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982d95ee48cc592fe3c1c7c27d64f1f2ef41604ac2b2d4edb23ca2a96654e10f2ec0b9c410217b3d2a4abccaf2367b5f4a3d23fd583b9a610cadaad671dc6af4

test:
  secret_key_base: 49274a6dbf925100823e29dec4b0cf664016f2acac36c771ddd9c93d8735f762ec01229d2febc30740c43dd59c0ea3ffd910a2e63c299a9ca7432af35c8eed1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
